CREATE TABLE USER (
    ID PRIMARY KEY,
    EMAIL VARCHAR(50) UNIQUE,
    PASSWORD VARCHAR(100),
    USERID PRIMARY KEY UUID

);

CREATE TABLE PROJECT (
    id UUID REFERENCES USER(USERID) ON DELETE CASCADE,
    PROJECT_NAME VARCHAR(50),
    PROJECT_DESC DESC,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE EVENTS(
    id PRIMARY KEY,
    project_id UUID NOT NULL REFERENCES PROJECT(id) ON DELETE CASCADE,
    event VARCHAR(150),
    properties JSONB DEFAULT '{}',
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE APIKEY (
    id PRIMARY key uuid gen_random_uuid,
    project_id PRIMARY key REFERENCES project(id) ON DELETE CASCADE,
    key VARCHAR(255) UNIQUE NOT NULL
)


